reclamations:
    path: /reclamations
    controller: App\Controller\ReclamationsController::index

new_reclamations:
    path: /reclamations/new
    controller: App\Controller\ReclamationsController::new

show_reclamations:
    path: /reclamations/{id}
    controller: App\Controller\ReclamationsController::show

edit_reclamations:
    path: /reclamations/{id}/edit
    controller: App\Controller\ReclamationsController::edit

delete_reclamations:
  path: /reclamations/{id}/delete
  methods: [DELETE]
  controller: App\Controller\ReclamationsController::delete
search_reclamations:
    path: /reclamations/search
    controller: App\Controller\ReclamationsController::search
new_index:
  path: /new_index
  controller: App\Controller\NewIndexController::index 

reponse_new:
    path: /reponse/new
    controller: App\Controller\ReponseController::new
add_reponse:
    path: /reclamations/{id}/Reponse
    controller: App\Controller\ReclamationsController::add_reponse
    
reclamations_stat:
    path: /reclamations/stat
    controller: App\Controller\ReclamationsController::stat
        
home:
    path: /home
    controller: App\Controller\HomeController::home


app_produit_statistics:
    path: /produit-statistics
    controller: App\Controller\ProduitController::produitStatistics
app_categorie_download_excel:
    path: /download-categories-excel
    controller: App\Controller\CategorieController::downloadCategoriesExcel
app_categorie_download_pdf:
    path: /download-categories-pdf
    controller: App\Controller\CategorieController::downloadCategoriesPdf
app_produit_download_pdf:
    path: /download-products-pdf
    controller: App\Controller\ProduitController::downloadProductsPdf
app_trier_par_nom:
    path: /trier-par-nom
    controller: App\Controller\CategorieController::trierParNom
app_trier_par_prix:
    path: /trier-par-prix
    controller: App\Controller\ProduitController::trierParPrix    
products:
    path: /products
    controller: App\Controller\ProduitController::indexfront
equipes:
    path: /equipes
    controller: App\Controller\EquipeController::indexfront
joueurs:
    path: /joueurs
    controller: App\Controller\JoueurController::indexfront
about:
  path: /about
  controller: App\Controller\AboutController::about
  methods: GET
app_trier_par_prix1:
    path: /trier-par-prixf
    controller: App\Controller\ProduitController::trierParPrix1 