reclamations:
    path: /reclamations
    controller: App\Controller\ReclamationsController::index

new_reclamations:
    path: /reclamations/new
    controller: App\Controller\ReclamationsController::new

show_reclamations:
    path: /reclamations/{id}
    controller: App\Controller\ReclamationsController::show

edit_reclamations:
    path: /reclamations/{id}/edit
    controller: App\Controller\ReclamationsController::edit

delete_reclamations:
  path: /reclamations/{id}/delete
  methods: [DELETE]
  controller: App\Controller\ReclamationsController::delete
search_reclamations:
    path: /reclamations/search
    controller: App\Controller\ReclamationsController::search
new_index:
  path: /new_index
  controller: App\Controller\NewIndexController::index 

reponse_new:
    path: /reponse/new
    controller: App\Controller\ReponseController::new
add_reponse:
    path: /reclamations/{id}/Reponse
    controller: App\Controller\ReclamationsController::add_reponse
    
reclamations_stat:
    path: /reclamations/stat
    controller: App\Controller\ReclamationsController::stat